name: .NET

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --results-directory reports --collect:"XPlat Code Coverage;Format=Cobertura,OpenCover"

  sonarcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: highbyte/sonarscan-dotnet@v2.2.1
      with:
        sonarProjectKey: OptimalChangeKataKey
        sonarProjectName:  OptimalChangeKata
        sonarOrganization: aimenux-sonar-cloud-key
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}